### ISSUE TITLE
Run CoreIntegrationTests Handler Error

### ISSUE THREAD

**Issue by windNight** [alexandre-spieser/mongodb-generic-repository#24]
modify connectionString Value with code:
const string connectionString = "mongodb://username:pwd@host1:port1,host2:port2/db?replicaSet=mongoSet";

then run CoreIntegrationTests handler  errors :

MongoDB.Driver.MongoConnectionException : An exception occurred while receiving a message from the server.
---- System.IO.EndOfStreamException : Attempted to read past the end of the stream.
   at MongoDB.Driver.Core.Connections.BinaryConnection.ReceiveBuffer()
   at MongoDB.Driver.Core.Connections.BinaryConnection.ReceiveBuffer(Int32 responseTo, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Connections.BinaryConnection.ReceiveMessage(Int32 responseTo, IMessageEncoderSelector encoderSelector, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.AcquiredConnection.ReceiveMessage(Int32 responseTo, IMessageEncoderSelector encoderSelector, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.WireProtocol.CommandUsingQueryMessageWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocol[TResult](IWireProtocol`1 protocol, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.Command[TResult](ICoreSession session, ReadPreference readPreference, DatabaseNamespace databaseNamespace, BsonDocument command, IEnumerable`1 commandPayloads, IElementNameValidator commandValidator, BsonDocument additionalOptions, Action`1 postWriteAction, CommandResponseHandling responseHandling, IBsonSerializer`1 resultSerializer, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableWriteCommandOperationBase.ExecuteAttempt(RetryableWriteContext context, Int32 attempt, Nullable`1 transactionNumber, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableWriteOperationExecutor.Execute[TResult](IRetryableWriteOperation`1 operation, RetryableWriteContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.BulkUnmixedWriteOperationBase`1.ExecuteBatches(RetryableWriteContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.BulkUnmixedWriteOperationBase`1.Execute(RetryableWriteContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.BulkMixedWriteOperation.ExecuteBatch(RetryableWriteContext context, Batch batch, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.BulkMixedWriteOperation.Execute(IWriteBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteWriteOperation[TResult](IWriteBinding binding, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteWriteOperation[TResult](IClientSessionHandle session, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.BulkWrite(IClientSessionHandle session, IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.<>c__DisplayClass23_0.<BulkWrite>b__0(IClientSessionHandle session)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSession[TResult](Func`2 func, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.BulkWrite(IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionBase`1.<>c__DisplayClass64_0.<InsertOne>b__0(IEnumerable`1 requests, BulkWriteOptions bulkWriteOptions)
   at MongoDB.Driver.MongoCollectionBase`1.InsertOne(TDocument document, InsertOneOptions options, Action`2 bulkWrite)
   at MongoDB.Driver.MongoCollectionBase`1.InsertOne(TDocument document, InsertOneOptions options, CancellationToken cancellationToken)
   at MongoDbGenericRepository.DataAccess.Create.MongoDbCreator.AddOne[TDocument,TKey](TDocument document) in D:\development\mongodb-generic-repository\MongoDbGenericRepository\DataAccess\Create\MongoDbCreator.cs:line 49
   at CoreIntegrationTests.Infrastructure.MongoDbTKeyDocumentTestBase`2.AddOne() in D:\Public\mongodb-generic-repository\CoreIntegrationTests\Infrastructure\MongoDbTKeyDocumentTestBase.cs:line 78
----- Inner Stack Trace -----
   at MongoDB.Driver.Core.Misc.StreamExtensionMethods.ReadBytes(Stream stream, Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Connections.BinaryConnection.ReceiveBuffer()

**Comment by windNight** [comment]
![Uploading image.png…](errors)

**Comment by alexandre-spieser** [comment]
Have a look here and edit the constants there:
https://github.com/alexandre-spieser/mongodb-generic-repository/blob/master/CoreIntegrationTests/Infrastructure/TestRepository.cs
Alternatively you can modify the class to look at the connection string in the app.config.
Tests are meant to run on localhost instances only - not replica sets, they drop collections, so be very careful to what you point them to if you are using this in your own code.

**Comment by windNight** [comment]
> Have a look here and edit the constants where needed:
> https://github.com/alexandre-spieser/mongodb-generic-repository/blob/master/CoreIntegrationTests/Infrastructure/TestRepository.cs
> Alternatively you can modify the class to look at the connection string in the app.config.
> Tests are meant to run on localhost instances only - not replica sets, they drop collections, so be very careful to what you point them to if you are using this in your own code.

I Solve this issue with that I remove BsonRepresentation in class Nested. Mybe the version of the MongoDb Need 3.4 or later?
also. UT is fialed in SumByDecimalAsync() and SumByDecimal();

**Comment by alexandre-spieser** [comment]
Try to use MongoDb 4.0. MnogoDb 3.4 is approaching end of life support.

**Comment by windNight** [comment]
remove BsonRepresentation in class Nested. or update MongoDb version
